
package com.inspur.qls.bpmclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProcessDispatcherImplService", targetNamespace = "http://process.job.qlsbpm.com/", wsdlLocation = "http://192.168.252.11:9912/process?wsdl")
public class ProcessDispatcherImplService
    extends Service
{

    private final static URL PROCESSDISPATCHERIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.inspur.qls.bpmclient.ProcessDispatcherImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.inspur.qls.bpmclient.ProcessDispatcherImplService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.252.11:9912/process?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.252.11:9912/process?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PROCESSDISPATCHERIMPLSERVICE_WSDL_LOCATION = url;
    }

    public ProcessDispatcherImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessDispatcherImplService() {
        super(PROCESSDISPATCHERIMPLSERVICE_WSDL_LOCATION, new QName("http://process.job.qlsbpm.com/", "ProcessDispatcherImplService"));
    }

    /**
     * 
     * @return
     *     returns ProcessDispatcher
     */
    @WebEndpoint(name = "ProcessDispatcherImplPort")
    public ProcessDispatcher getProcessDispatcherImplPort() {
        return super.getPort(new QName("http://process.job.qlsbpm.com/", "ProcessDispatcherImplPort"), ProcessDispatcher.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessDispatcher
     */
    @WebEndpoint(name = "ProcessDispatcherImplPort")
    public ProcessDispatcher getProcessDispatcherImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://process.job.qlsbpm.com/", "ProcessDispatcherImplPort"), ProcessDispatcher.class, features);
    }

}
